[package]
name = "lycifer3/saveguard"
description = "SaveGuard - A drop-in safety layer for Roblox player saves. Minimize data loss, protect against wipes, handle crashes gracefully"
version = "0.1.0"
license = "MIT"
authors = ["lycifer3"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
exclude = ["tests", "examples", "docks"]

[dependencies]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"

